import { Color, Texture, Vector2 } from "three";
export declare function getJson(url: string): unknown;
export declare const inertiaTo: (current: number, target: number, changeBy: number, minCutoffValue?: number) => number;
export declare function convert255(v: number): number;
export declare function hexToColor(hex: string): Color;
export declare function rgbToHex(r: number, g: number, b: number): number;
export declare const isTouchDevice: () => any;
export declare const random: (a?: number, b?: number) => any;
export declare const randomInt: (a?: number, b?: number) => any;
export declare const pick: (ary: []) => any;
export declare const getObjectPropByKey: (obj: any, key: string) => any;
export declare const getClassFromString: (name: string) => string;
export declare const timeout: (ms: number) => any;
export declare const fit: (value: number, low1: number, high1: number, low2: number, high2: number) => number;
export declare const bellCurve: (value: number) => number;
export declare const lerp: (v0: number, v1: number, t: number) => number;
export declare const hexToRgb: (hex: string) => {
    r: any;
    g: any;
    b: any;
} | null;
export declare const strToBool: (s: string) => any;
export declare const doesUrlKeyExist: (key: string) => boolean;
export declare const getUrlKeyValue: (key: string) => string | null | undefined;
export declare const isIOS: () => any;
export declare const isSafari: () => any;
export declare const isChrome: () => any;
export declare const isFirefoxIOS: () => any;
export declare const getDeviceType: () => "desktop" | "tablet" | "mobile";
export declare const getTextureMapData: (heightmap: Texture) => any;
export declare const getTexturePixelValue: (imageData: ImageData, coordinate: Vector2) => {
    r: number;
    g: number;
    b: number;
    a: number;
};
export declare const loadAudioBuffer: (url: string, audioContext: AudioContext) => any;
export declare const loadBinaryBuffer: (url: string) => any;
